include:
  - project: library/ci-templates
    ref: main
    file: /docker-image.yml
  - project: library/ci-templates
    ref: main
    file: /jobs/lint.yml

shellcheck:
  extends: .shellcheck
  variables:
    SHELL_FILES: run.sh
    SHELLCHECK_SEVERITY: warning
